return {
  {
    "nvim-treesitter/nvim-treesitter",
    lazy = false,
    build = ":TSUpdate",
    branch = "main",
    -- cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
    -- opts_extend = { "ensure_installed" },
    -- opts = {
    --   indent = { enable = true },
    --   highlight = { enable = true },
    --   folds = { enable = true },
    --   ensure_installed = {
    --     "bash",
    --     "c",
    --     "diff",
    --     "html",
    --     "javascript",
    --     "jsdoc",
    --     "json",
    --     "jsonc",
    --     "java",
    --     "lua",
    --     "luadoc",
    --     "luap",
    --     "markdown",
    --     "markdown_inline",
    --     "printf",
    --     "python",
    --     "query",
    --     "regex",
    --     "toml",
    --     "tsx",
    --     "typescript",
    --     "vim",
    --     "vimdoc",
    --     "xml",
    --     "yaml",
    --   },
    -- },
  },
  {
    "nvim-treesitter/nvim-treesitter-textobjects",
    branch = "main",
    dependencies = { "nvim-treesitter/nvim-treesitter" },
  },
}
